POST http://localhost:3333/sessions
Content-Type: 'application/json'

{
  "email":"example3@gmail.com",
  "password":"123456"
}

###

POST http://localhost:3333/users
Content-Type: 'application/json

{
  "name":"teste",
  "email":"example3@gmail.com",
  "password":"123456"
}

###

GET http://localhost:3333/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZjM3NThmOC0yNzU5LTRlYjItYmI1ZC04YWQ3Njg3MTI3YjkiLCJpYXQiOjE3MDg0NzMzNzF9.gVqzBKz1CkmMZn07D5GV_pQ2qDOuMWaeW0eOOSA5AVE